# Generated by Django 5.2.7 on 2026-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='iletisim',
            old_name='mesaj',
            new_name='adres',
        ),
        migrations.RemoveField(
            model_name='iletisim',
            name='isim',
        ),
        migrations.RemoveField(
            model_name='iletisim',
            name='tarih',
        ),
        migrations.AddField(
            model_name='iletisim',
            name='telefon',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='aciklama',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iletisim',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
